name: Build Android
on:
  push:
    branches:
      - master
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn install
      - name: Run tests with coverrage
        run: |
          yarn test
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn install
      - name: Create local.properties file
        run: |
          printf 'expenses.base.url="http://10.0.2.2:3000/"' >> $HOME/work/gharama-app/gharama-app/android/local.properties
      - name: Run Android tests
        run: |
          cd android && ./gradlew clean && ./gradlew cleanBuildCache && ./gradlew app:test --stacktrace
